#!/bin/sh

DIR=$(dirname $(realpath $0))

cd $DIR

exec setuidgid www /usr/local/bin/uwsgi \
    --socket=/tmp/hilite.me.sock \
    --pythonpath="$DIR" \
    --home=env \
    --master \
    --processes=5 \
    --harakiri=30 \
    --max-requests=1000 \
    --module="main:app"
